### ISSUE TITLE
Icon Display not working

### ISSUE THREAD

**Issue by rk-kontur** [Ellpeck/ObsidianCustomFrames#117]
I cannot make the custom frame dsplay any icon. I tried full links to my icon folder, only Lucide names or just typing inside the little settings window. Nothing so far worked out.

Am I doing something wrong? Where are the icons supposed to be and what does the properly filled out field look like?

THANK YOU!

**Comment by rk-kontur** [comment]
Huh!

Thanks for getting back, but this is exactly what I tried. I even went so far as to look up the Lucide names on the weblink.

Could it be that I am keeping thhe icons in a dedicated folder set through iconize plugin?

https://github.com/FlorianWoelki/obsidian-iconize

**Comment by Ellpeck** [comment]
Hi! That shouldn't really make a difference. Have you tried disabling the Obsidian theme you're using? It might be interfering with Obsidian's default set of Lucide icons.

**Comment by Ellpeck** [comment]
There isn't meant to be any autocomplete, as Obsidian doesn't provide a full list of the Lucide icons it supports. 

Please try without any themes or snippets enabled :)

**Comment by rk-kontur** [comment]
All snippets disabled. Theme switched to Standard. REstarted

![image](https://github.com/Ellpeck/ObsidianCustomFrames/assets/90571507/0bf75f79-ca92-4a21-8756-7c304f6a992c)

**Comment by Ellpeck** [comment]
How many distinct icons have you tried with? Maybe the one you're trying to use just isn't supported by Obsidian :(

**Comment by rk-kontur** [comment]
Do you have one that you can confirm working? Otherwise there are quite a few to try.

Apart from that, I never had icon trouble elsewhere...

**Comment by Ellpeck** [comment]
All the icons that the default frame templates use are confirmed to work, obviously. You can just create a frame from one of the default templates in the Custom Frames settings, or you can see the full list of templates and their settings [in this repo](https://github.com/Ellpeck/ObsidianCustomFrames/blob/master/src/settings.ts).

**Comment by Ellpeck** [comment]
Hm, that's a little annoying. There used to pretty much be community consensus that Obsidian supported all Lucide icons up to a specific version, along with some of its own icons. Back when I originally made the plugin, I just tried a bunch of randomly selected icons from the Lucide catalog, and they all worked, so I must've just been lucky then. 

I'll make sure to change the wording of the icon section to point out that some icons might not work!

As for the preset: I generally only create presets for apps I use myself, since a big part of the presets is that they usually contain custom styling to make the site work better in the context of Obsidian (like removing unnecessary elements, and making sites that usually aren't made for a narrow layout work in the Obsidian sidebar. If you use the site frequently, feel free to create and submit a template via a pull request! There's more info about that [in the README](https://github.com/Ellpeck/ObsidianCustomFrames/blob/master/src/settings.ts) :)
