### ISSUE TITLE
Tabs Not Running in Background

### ISSUE THREAD

**Issue by julroger2013** [Ellpeck/ObsidianCustomFrames#28]
I don't know whether to report this is a feature request or a bug. 

One of the custom frames that I have been using is [Pomodone App](https://pomodoneapp.com/), a pomodoro work timer that automatically imports tasks from Todoist and generates a timesheet specifying what Pomodoros were completed on what task at what time. 

Unfortunately, the page seems to refresh (and so the timer stops running) if I select another tab in the sidebar and then later return to the Pomodone tab. 

This might be an inherent limitation of Obsidian, but it would be nice if the timer could keep running in the background. 

Failing that, could you add an option to specify in which sidebar (left or right) custom frames are to open? Having more flexibility in where the frames automatically open would make it easier to keep Pomodone constantly running in one sidebar while using the other sidebar to manage the tabs that I will actively switch between.

**Comment by Ellpeck** [comment]
Hi, thanks so much for the issue report! 

Unfortunately, I don't think this is possible in Obsidian, and I'm not really interested in pursuing it as a feature either, since it probably wouldn't be worth all the effort.

Custom Frames only open to the right if you permanently close them prior to opening them. If you open them once, and then drag the pane's tab to any other sidebar, or any other location you want, it'll stay there as long as you don't Right Click -> Close it. This works with any Obsidian panes, and isn't exclusive to Custom Frames!
