### ISSUE TITLE
Personal account security concern

### ISSUE THREAD

**Issue by Gourav1910** [Ellpeck/ObsidianCustomFrames#30]
Is it safe to login into our google keep account through the custom frames plugin? Where does it store the password and who can access my password? Please clarify, this plugin is so awesome for me but I only have this security concern.

**Comment by Ellpeck** [comment]
Hi! Custom Frames doesn't storage any information about anything. 

All it does is display a small browser window (that's the part called a webview or iframe!) in Obsidian. The source of the browser window doesn't matter, because any information (local storage and cookies) is always stored in the same location, which is determined by Electron, the underlying framework that Obsidian uses.

Either way, this means that Custom Frames never gets to see your passwords or any other personal information.

**Comment by Gourav1910** [comment]
Oh thanks, now your plugin is one of my fav plugins in obsidian😊😊😊.
