### ISSUE TITLE
Feature Request: Option to open in a new pane 

### ISSUE THREAD

**Issue by Flummic** [Ellpeck/ObsidianCustomFrames#33]
I really love this plugin and use it every single day to pull todoist/google keep and other sites into my obsidian, which is kind of my save space away from the distractions of my web browser!

I currently have set a todoist-Icon in the sidebar/ribbon which I use very frequently. One "painpoint" I have is that I often want Todoist to open in a new pane and not on the current one, so I can for example have my daily doc open next to the todoist pane.
Currently I have to open another pane in advance, select it and then press the Todoist-Ribbon-Button to open it in that second/new pane. 
**I would love to have a setting in the Custom-Frames-Plugin, which allows me to automativally open a frame in a new pane from the obsidian ribbon.** 

If you want to go overboard, we could also add a "key-modifier" to do that -> normal click still opens it in the current pane but Ctrl+Click opens it in a new one :)

**Comment by Sam-Kearns** [comment]
+1. I have this same pain point.

Note that for all standard Obsidian ribbon icons (Open today's daily note, Graph View, etc), when you click the icon, it replaces the content of the current pane, but if you Ctrl+click the icon, it opens in a new pane. This is the same as the behavior for all internal links in Obsidian panes (click opens in current pane, ctrl+click opens in a new pane).

Rather than a plugin setting as suggested by Flummic above, I would prefer Custom Frames to implement the ctrl+click behavior that is implemented by all standard ribbon icons.

**Comment by jokysatria** [comment]
Thank you for implementing this feature!
