### ISSUE TITLE
I can't install your plugin!

### ISSUE THREAD

**Issue by Jack-KkKk** [Ellpeck/ObsidianCustomFrames#4]
Thank you for your work!

I'm interested in your work, but I can't install your plugin on my Obsidian. 

When I try to install your plugin, it didn't work, and I see the message 'No appropriate version found' 

Please check!

**Comment by Ellpeck** [comment]
The plugin is currently available only for Obsidian insider versions 0.14.3 and upwards, due to changes made that allow more freedom in the usage of iframes. If you don't need those special features (which are the ones that allow sites like Google Keep to work), you can download the plugin manually from the Releases tab and put it into your vault's plugins folder.
