### ISSUE TITLE
[Feature Request] - Copy link to current page into clipboard

### ISSUE THREAD

**Issue by rapatel0** [Ellpeck/ObsidianCustomFrames#48]
I have gmail embedded in a view and I would like to pull the link to the email thread and embed it into a note. 

Current Problems:
- There is no way to access the current URL for a view. The right click menu doesn't work inside the frame and the Address Bar is not shown

SUPER nice to have:
- Url is clipped and automatically created as an view that can be embedded in a note.  (Note: This is trivial to implement as an Quick add command if the URL is copied to clipboard)

**Comment by Ellpeck** [comment]
Hi, two things about your request:

- If you're using Custom Frames' pane mode (which is really the preferred way to use the plugin, especially since you can just use iframes in notes instead), you can already copy the current URL by right-clicking the pane title and selecting "Copy link". Adding these commands to markdown mode is already on the [roadmap](https://github.com/Ellpeck/ObsidianCustomFrames#%EF%B8%8F-roadmap). 

- If you want to embed an anchor or sub-page of one of your frames in a note, there's a dedicated feature for that, the `urlSuffix` setting. You can read more about it in [the README](https://github.com/Ellpeck/ObsidianCustomFrames#%EF%B8%8F-markdown-mode), too.

Good luck!

**Comment by rapatel0** [comment]
Cool The copy link command works with the updated link 

However, I still think it would be good to have the copy link command as a modal available in command pallette. This would make it much easier to use automation with Quickadd and other hotkey plugins. It's a bit of a pain now to move the URL around.
