### ISSUE TITLE
Pls Add url icon in sidebar similar speed dial in browser 

### ISSUE THREAD

**Issue by Connor-yang96** [Ellpeck/ObsidianCustomFrames#51]
Please Add url icon in sidebar similar speed dial in browser .

![image](https://user-images.githubusercontent.com/81000027/182810190-29c941b0-7223-40d7-9577-97c0be0e91df.png)

The advanced table plugin can show icon in sidebar. it's very convince that If use the same feature for open url .

**Comment by Ellpeck** [comment]
You can already display a custom frame's "Open" button in the left sidebar. If that's not what you want, I might be misunderstanding your request.

**Comment by Connor-yang96** [comment]
> 

the left sidebar has not enough space for more urls and mixed with plugin icons.

My means the pane sidebar, please try to open advanced table plugin settings - "show icon in sidebar".

**Comment by Ellpeck** [comment]
Ah. I'm sorry, I'm not interested in adding a feature like this right now.

**Comment by Connor-yang96** [comment]
Why have no interested ?
That's very convince for bookmark more urls, for switch open urls. 

Why have no interested ?

**Comment by Ellpeck** [comment]
While I think your idea is nice, I also think it's out of scope of what this plugin is intended to do. While I realize that the image you showed is just an example, it contains a lot of stuff that I don't expect people to want to open within Obsidian. While it makes sense to view your emails, your calendar and your notes using Custom Frames, I don't think anyone would reasonably want to look at Amazon or watch Netflix within Obsidian rather than just opening it in their browser normally. With that in mind, I think the left sidebar feature is more than enough for quickly accessing your frames.

Also, it sounds like you might have a lot of clutter in your sidebar that you don't actually use if it's getting bad enough that you claim there isn't enough space for additional buttons. I recommend a plugin like [Commander](https://github.com/phibr0/obsidian-commander) which allows you to hide sidebar buttons that you don't actually use.

**Comment by Connor-yang96** [comment]
If you know beam browser, might you got my idea . Why I need more urls. 
https://twitter.com/getonbeam?lang=en

It's almost all informations we got from browser, right ? 

The beam browser is taking notes within the browser ,Text, images, videos, Figma boards, Spotify..capture the whole web! 

I want to try combine browser within notes app (Obsidian) to reduce steps, speed up taking notes between browser and notes app(Obsidian). 

Left is browser ,right is taking notes , the two parts combined within only 1 app, We don't switch app to another app. 
 
That's very wonderful. right ?

**Comment by Ellpeck** [comment]
As I said, this is out of scope for what I want Custom Frames to be able to do.
