### ISSUE TITLE
Width 100% of the active note(Custom_Frame) 

### ISSUE THREAD

**Issue by igorpereirabr1** [Ellpeck/ObsidianCustomFrames#53]
Hi, first of all, congratulations, this is one of the most interesting plugins from Obsidian.

Talking about my issue, I would like to know if there is a way to force the width of a custom_frame to 100%

![image](https://user-images.githubusercontent.com/29541571/183499376-f1442e66-0bae-44db-a9c4-e1afd3b955d8.png)

Thanks!

**Comment by Ellpeck** [comment]
Hi! As you can see in [the README](https://github.com/Ellpeck/ObsidianCustomFrames#%EF%B8%8F-markdown-mode), you can add any custom CSS to a frame when it's in Markdown mode. 

Putting a `width: 100%` might be enough, but I'm not sure, since the element the frame is in might be too nested compared to the element that has the max width you're referring to. If that doesn't work, you can try to find other style options online that might work for this use case. If you find a good one, do let me know here so I can add it as an example!

**Comment by igorpereirabr1** [comment]
I'll try this too, I'm able to achieve the expected result with the bellow html code:

<iframe src="http://localhost:8888/lab" style="position:fixed; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;"> </iframe>

**Comment by Ellpeck** [comment]
The custom frame is also just an `iframe` (or a `webview` on Desktop), so you should be able to apply the same style to it to make it work!

**Comment by igorpereirabr1** [comment]
I'll try to do this... I'm terrible with html and css.. hehehe

**Comment by igorpereirabr1** [comment]
Hi, just in case someone else needs a similar solution, I've included the below css in my custom frame:

.custom-frames-frame {
	position:fixed !important;
	top:35px !important;
	left:1px !important;
	bottom:35px !important;
	right:1px !important;
	width:100% !important;
	height:100% !important;
	border:none !important;
	margin:0 !important;
	padding:0 !important;
	overflow:hidden !important;
	z-index:999999 !important;
}

the output was:

![image](https://user-images.githubusercontent.com/29541571/183908844-4c61d233-1a3d-4088-a210-3f7c253fbb60.png)
