### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by WellingtonmpdNeves** [Ellpeck/ObsidianCustomFrames#91]
First congratulations for the work, it has really helped me a lot to optimize my flow of notes. I have two questions:
It is possible to have the page automatically translated into the language of your choice (Portuguese-Brazil) on load.
Second, there is a way to stay logged in to a specific page, like UpToDate, without having to repeatedly enter your login credentials.
Thank you in advance for your attention and effort in producing your plugin ✌️

**Comment by Ellpeck** [comment]
> It is possible to have the page automatically translated into the language of your choice (Portuguese-Brazil) on load.

Hi! This should automatically happen based on the setting you have Obsidian set to, since it changes the setting that the overall Electron instance is set to. If that is not the case, please open a new issue with a feature request. Thanks!

>  Second, there is a way to stay logged in to a specific page, like UpToDate, without having to repeatedly enter your login credentials.

Cookies and local storage are stored normally through Obsidian as they would be otherwise. This means that all login data that any given site stores will be restored next time you enter the site. It might be that the site you're trying don't support what is usually known as a "remember me" feature, though. 

Cookies and local storage might also work more inconsistently in `iframe` mode, so I recommend always using webview mode for your frames if possible.
