### ISSUE TITLE
Local HTML pages?

### ISSUE THREAD

**Issue by Aetherinox** [Ellpeck/ObsidianCustomFrames#96]
Hi,

I have a few HTML pages (with css / js) I'd like to load in these frames. However, I've tried a few ways, and I can't seem to get it to work.
Is this a possibility, or can it be implemented as a feature?

**Comment by Ellpeck** [comment]
Sorry, but there are no plans to implement this as a feature. To serve HTML effectively, it needs to be served through a web server to avoid various mechanics breaking, and web server capabilities would be out of scope of this plugin. Simply opening HTML files in a custom frame is not a feature I'm particularly fond of, since it would likely cause a lot of people confusion over certain web features they're used to not working correctly.
