### ISSUE TITLE
Support for Pinboard (API tokens)?

### ISSUE THREAD

**Issue by FilSalustri** [Ellpeck/ObsidianCustomFrames#97]
I use pinboard.in to bookmark links. While I can embed my pinboard with CustomFrames, it only shows some links - very likely because the CustomFrame isn't providing the appropriate API token that pinboard expects.

Questions:

1. Is there a way to provide an API token to a Custom frame in CustomFrames?
2. If not, can we add this as a feature requests?

Thanks for a very useful plugin!

**Comment by Ellpeck** [comment]
I don't think I understand what you mean by "API token"? Do you mean a token that a site supplies to keep you logged in? If so, you have to log in to the site you're trying to use through the custom frame, or through another custom frame that opens to the login page directly, so that Obsidian's cache can save your login data like a normal browser would.

**Comment by FilSalustri** [comment]
Oh, nuts, it's my fault. The pane in which the pinboard frame was rendering wasn't wide enough to accommodate pinboard's static page width, so I missed the topbar item to log in.

Everything works as it should. Sorry for the trouble.
